<a href="https://colab.research.google.com/github/eildes06/freelance_works/blob/main/Payment_val_control.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
data = pd.read_excel('/content/NEXT ALL DATA-Test File.xlsx')
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 790 entries, 0 to 789
Data columns (total 40 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Batch- ID                                790 non-null    object
 1   ExportDate                               790 non-null    object
 2   MAWBno                                   41 non-null     float64
 3   Tracking Number                          790 non-null    int64
 4   CustomerOrderNo                          790 non-null    int64
 5   ImporterTAXID                            790 non-null    object
 6   ImporterName                             790 non-null    object
 7   ImporterFirstName                        720 non-null    object
 8   ImporterLastName                         720 non-null    object
 9   ImporterAddress                          790 non-null    object
 10  ImporterCountry                          790 non-null    object
 11  ImporterPostcode                         790 non-null    object
 12  ImporterCity                             790 non-null    object
 13  ImporterEmail                            790 non-null    object
 14  ImporterPhone                            790 non-null    object
 15  CustomsValueTRY                          790 non-null    float64
 16  EURtoTRYRate                             790 non-null    float64
 17  CustomsValueEUR                          790 non-null    float64
 18  CustomsTaxValTRY                         790 non-null    float64
 19  AdminFeeTRY                              713 non-null    float64
 20  TotalValueTRY                            790 non-null    float64
 21  NetReceivedValue                         550 non-null    object
 22  PaymentValControl                        550 non-null    object
 23  PaymentReceived                          549 non-null    object
 24  ShipmentReady                            550 non-null    object
 25  PaymentMethod                            550 non-null    object
 26  PaymentSenderInfo                        550 non-null    object
 27  PaymentReceivedDate                      550 non-null    object
 28  PaymentNotes                             550 non-null    object
 29  Manifest                                 41 non-null     object
 30  ManifestDate                             41 non-null     object
 31  InvoiceReady                             0 non-null      float64
 32  InvoiceDate                              0 non-null      float64
 33  FullRefund                               1 non-null      object
 34  RefundNotes (Iadeler ile Ilgili Notlar)  2 non-null      object
 35  Notes                                    2 non-null      object
 36  Unnamed: 36                              0 non-null      float64
 37  Unnamed: 37                              0 non-null      float64
 38  Unnamed: 38                              0 non-null      float64
 39  Unnamed: 39                              221 non-null    float64
dtypes: float64(13), int64(2), object(25)
memory usage: 247.0+ KB

/usr/local/lib/python3.10/dist-packages/openpyxl/worksheet/_reader.py:312: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)

In [ ]:
data["NetReceivedValue"]

0           NaN
1           NaN
2           NaN
3           NaN
4           NaN
5           NaN
6           NaN
7           NaN
8           NaN
9           NaN
10          NaN
11          NaN
12          NaN
13          NaN
14          NaN
15          NaN
16          NaN
17          NaN
18          NaN
19          NaN
20          NaN
21          NaN
22       370.31
23          NaN
24          NaN
25          NaN
26          NaN
27          NaN
28          NaN
29          NaN
30          NaN
31          NaN
32       161.74
33          NaN
34          NaN
35          NaN
36          NaN
37          NaN
38          NaN
39          NaN
40          NaN
41       844.75
42       325.75
43          NaN
44            0
45       317.65
46          NaN
47       566.84
48          NaN
49       247.02
50          NaN
51       321.39
52       632.72
53        206.5
54       370.67
55          NaN
56       604.12
57          NaN
58       649.87
59       236.92
60       822.97
61       262.14
62        854.2
63       307.01
64          NaN
65          NaN
66          NaN
67       326.32
68        421.6
69      5743.88
70       873.48
71        950.8
72       555.47
73        699.4
74        702.8
75       796.68
76        244.9
77        926.8
78          351
79          NaN
80        423.7
81       873.48
82        351.4
83       362.37
84        683.2
85        853.6
86       272.03
87       280.21
88          NaN
89          NaN
90       948.96
91       276.45
92       414.28
93       543.22
94       931.56
95       870.02
96       243.88
97       292.22
98       369.52
99       708.14
100      304.95
101      365.68
102      180.96
103      146.38
104      252.28
105      933.88
106      566.57
107      904.88
108      872.45
109      336.78
110      320.41
111      759.28
112      861.53
113      943.38
114      894.27
115      836.98
116      554.14
117      544.18
118      836.98
119      780.28
120      225.86
121      599.31
122      987.28
123      942.28
124      246.44
125      917.38
126       992.8
127      763.78
128      926.68
129       463.8
130      925.78
131      872.45
132      769.98
133         NaN
134      788.08
135      209.46
136         NaN
137         NaN
138         NaN
139         NaN
140         NaN
141         NaN
142      446.09
143         NaN
144         NaN
145         NaN
146         NaN
147         NaN
148         NaN
149         NaN
150      618.58
151         NaN
152         NaN
153         NaN
154         NaN
155         NaN
156         747
157         NaN
158         NaN
159         NaN
160         NaN
161         NaN
162         NaN
163         NaN
164         NaN
165         256
166         NaN
167         NaN
168         NaN
169         NaN
170      725.29
171         NaN
172         NaN
173      675.14
174         NaN
175         NaN
176         NaN
177      153.49
178      394.99
179         NaN
180         NaN
181         NaN
182         NaN
183         NaN
184         NaN
185      866.82
186         NaN
187      233.59
188         NaN
189      880.96
190         NaN
191      578.27
192      787.36
193      247.36
194      280.36
195         NaN
196      255.46
197      271.66
198         NaN
199         NaN
200         NaN
201      455.19
202      438.46
203      397.89
204         NaN
205         NaN
206         NaN
207      876.22
208      202.93
209      192.92
210      274.78
211      621.12
212      947.77
213      738.29
214         NaN
215      980.51
216      225.66
217      710.52
218      239.52
219      635.83
220      927.15
221      991.62
222      242.03
223         NaN
224      258.41
225      389.67
226      698.22
227      637.85
228      570.25
229      459.02
230     4162.25
231         NaN
232         874
233      725.76
234      193.13
235      947.67
236      418.22
237      544.22
238      524.72
239      945.92
240       690.9
241      603.59
242      562.36
243      838.84
244      459.02
245      135.53
246      491.12
247      258.95
248      138.32
249      586.92
250      693.63
251      975.02
252      637.24
253      906.44
254      377.72
255      948.58
256      143.71
257      463.84
258      341.37
259      312.19
260      405.81
261      897.82
262      996.34
263      914.19
264      881.45
265         NaN
266      881.45
267      881.45
268      914.19
269      897.82
270      914.19
271      866.89
272      766.99
273      492.19
274         NaN
275      931.17
276      939.35
277      499.09
278      734.59
279      320.59
280      258.17
281       568.4
282      471.59
283      668.03
284      666.79
285         NaN
286      450.98
287      866.89
288      627.41
289      438.55
290         NaN
291         NaN
292         NaN
293         NaN
294      833.15
295         NaN
296         NaN
297         NaN
298         NaN
299         NaN
300         NaN
301         NaN
302         NaN
303         NaN
304         NaN
305      506.39
306         NaN
307         NaN
308         NaN
309         NaN
310         NaN
311      955.62
312       509.1
313         777
314      342.26
315       980.1
316       915.6
317         703
318     1014.34
319       859.2
320       394.9
321       842.7
322      843.06
323       939.3
324       420.9
325       216.9
326       923.4
327       988.5
328       786.6
329       599.1
330      736.05
331       923.1
332      559.61
333      617.82
334      739.99
335         NaN
336       260.1
337      309.52
338       923.1
339      133.08
340      424.11
341      186.44
342       491.1
343         984
344       596.6
345      391.67
346      247.98
347       731.8
348      358.63
349       654.8
350      1019.8
351      836.69
352      602.36
353      794.03
354      746.18
355      672.39
356         NaN
357         NaN
358         NaN
359         NaN
360      556.67
361      174.81
362         NaN
363         NaN
364         NaN
365      469.99
366      970.39
367      342.75
368         NaN
369      931.69
370      949.09
371         NaN
372         NaN
373      706.66
374      929.62
375      867.78
376      950.23
377      847.16
378      392.13
379         966
380       417.9
381      355.36
382      487.02
383       359.7
384         NaN
385         NaN
386      283.06
387      294.22
388      941.75
389      543.76
390      366.33
391      260.87
392      490.66
393    4.067.65
394      801.76
395      895.06
396         NaN
397         NaN
398      842.56
399      867.16
400      672.85
401         NaN
402      339.46
403      671.03
404         NaN
405      297.55
406      662.85
407      835.04
408      359.39
409      886.88
410      664.67
411      310.28
412      277.54
413      260.87
414      462.16
415         NaN
416         NaN
417      664.67
418      885.66
419      993.58
420      542.26
421      736.51
422      392.13
423      343.02
424      584.33
425      705.41
426      532.44
427      901.38
428         343
429     1008.08
430      484.54
431      843.41
432      426.04
433      245.36
434      328.12
435      261.73
436      212.62
437      667.95
438      688.56
439      900.41
440     1035.67
441       278.1
442      729.19
443      466.96
444      459.99
445     1027.49
446      162.34
447      630.97
448      819.83
449     1025.67
450      368.74
451      786.71
452       335.7
453      934.12
454      985.61
455      561.24
456      639.45
457      409.36
458      568.01
459      997.91
460     1008.08
461      967.77
462      433.92
463      957.16
464      311.14
465         NaN
466      4590.5
467      566.27
468      967.34
469         NaN
470     1009.48
471         NaN
472      927.29
473     1005.89
474      884.39
475      962.99
476      543.29
477      665.99
478      237.36
479      417.12
480      930.59
481         NaN
482      786.97
483      237.36
484      959.46
485      673.19
486      516.25
487      437.99
488      959.46
489      253.73
490      706.63
491      943.09
492      901.86
493      569.09
494       838.2
495      261.91
496         NaN
497      659.73
498      434.75
499      804.03
500      673.33
501      738.33
502      845.13
503      820.23
504         551
505      737.43
506      616.53
507         NaN
508         NaN
509      503.56
510      236.79
511         NaN
512         NaN
513         NaN
514      762.03
515         NaN
516      932.38
517      350.72
518      852.13
519      643.26
520      351.94
521      458.65
522         NaN
523      835.18
524       319.2
525      179.75
526      269.78
527      787.56
528      245.23
529       319.5
530      762.58
531      879.42
532      441.97
533     1051.91
534      299.68
535      294.34
536      442.28
537      491.39
538      967.03
539       983.7
540      564.75
541         NaN
542         NaN
543      318.89
544      159.13
545      710.56
546       482.9
547      876.39
548         NaN
549      901.55
550      524.73
551      630.53
552      474.71
553         897
554      819.58
555      297.88
556      835.46
557      599.68
558      269.48
559         NaN
560      236.74
561      979.46
562     1014.88
563         NaN
564      441.85
565       425.6
566     1005.88
567      687.83
568      201.88
569        1061
570      655.09
571     1057.06
572      474.41
573      659.33
574      704.11
575     1002.41
576         NaN
577      873.87
578      314.26
579         NaN
580      701.59
581      971.79
582      242.29
583      640.39
584      591.49
585         NaN
586         NaN
587      572.84
588     1037.59
589      867.49
590      869.89
591      496.99
592      909.04
593      974.82
594     1013.59
595      856.59
596      671.37
597      720.78
598      404.59
599      474.62
600      441.58
601         NaN
602      916.74
603         NaN
604         NaN
605         NaN
606         NaN
607         NaN
608         NaN
609         NaN
610       258.9
611     1042.53
612         NaN
613         NaN
614         NaN
615         NaN
616         NaN
617         NaN
618      709.02
619    4,453.88
620      340.15
621      758.35
622       827.6
623      450.93
624       373.3
625      627.06
626      697.08
627      558.85
628      647.67
629     1041.74
630      237.51
631      600.44
632         NaN
633       410.3
634      779.84
635      937.64
636      715.27
637         NaN
638      426.07
639      243.14
640      333.14
641      951.43
642      259.34
643    1,044.49
644       688.9
645       409.7
646      512.16
647      901.04
648         NaN
649      524.59
650      311.48
651      820.16
652      913.84
653      450.14
654    1.010.54
655      283.81
656      585.83
657      721.64
658      393.93
659      927.78
660      262.06
661      811.64
662      656.16
663      629.48
664      623.11
665      901.71
666      385.14
667      762.56
668      819.86
669      949.34
670      762.56
671         NaN
672      697.23
673      196.73
674      576.28
675         NaN
676      351.29
677      674.47
678         983
679       697.2
680      738.56
681         504
682      270.67
683         NaN
684         NaN
685       812.1
686      649.46
687         NaN
688      430.74
689         NaN
690      259.76
691      592.31
692      951.55
693      221.26
694      468.63
695      631.72
696      982.46
697      701.45
698      872.01
699      488.01
700       749.3
701         280
702         NaN
703      271.53
704      609.81
705      591.66
706      878.44
707      885.81
708         NaN
709      890.56
710      205.71
711      908.61
712      361.87
713      286.11
714      709.11
715      406.71
716      189.68
717      468.58
718      829.57
719      350.01
720       911.6
721      733.08
722         NaN
723      271.23
724      9354.4
725      297.76
726       642.1
727         NaN
728         NaN
729      342.33
730         NaN
731         NaN
732      600.27
733      480.33
734         NaN
735      781.23
736         NaN
737      599.66
738        1052
739      667.57
740      549.03
741      707.89
742      660.32
743      601.48
744      953.13
745           0
746         NaN
747     1018.61
748      799.13
749      854.61
750     1298.76
751         NaN
752         NaN
753         NaN
754         NaN
755         NaN
756         NaN
757         NaN
758         NaN
759         NaN
760         NaN
761         NaN
762         NaN
763         NaN
764         NaN
765         NaN
766         NaN
767         NaN
768         NaN
769         NaN
770         NaN
771         NaN
772         NaN
773         NaN
774         NaN
775         NaN
776         NaN
777         NaN
778         NaN
779         NaN
780         NaN
781         NaN
782         NaN
783         NaN
784         NaN
785         NaN
786         NaN
787         NaN
788         NaN
789         NaN
Name: NetReceivedValue, dtype: object

In [ ]:
data["NetReceivedValue"] = data["NetReceivedValue"].str.replace(',', '')

In [ ]:
data["NetReceivedValue"] = data["NetReceivedValue"].str.replace('.', '',1)

<ipython-input-4-dfd363be315b>:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  data["NetReceivedValue"] = data["NetReceivedValue"].str.replace('.', '',1)

In [ ]:
data["NetReceivedValue"] = data["NetReceivedValue"].astype(float)

In [ ]:
data.head()

,Batch- ID,ExportDate,MAWBno,Tracking Number,CustomerOrderNo,ImporterTAXID,ImporterName,ImporterFirstName,ImporterLastName,ImporterAddress,ImporterCountry,ImporterPostcode,ImporterCity,ImporterEmail,ImporterPhone,CustomsValueTRY,EURtoTRYRate,CustomsValueEUR,CustomsTaxValTRY,AdminFeeTRY,TotalValueTRY,NetReceivedValue,PaymentValControl,PaymentReceived,ShipmentReady,PaymentMethod,PaymentSenderInfo,PaymentReceivedDate,PaymentNotes,Manifest,ManifestDate,InvoiceReady,InvoiceDate,FullRefund,RefundNotes (Iadeler ile Ilgili Notlar),Notes,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39
0,Batch-100,2023-02-20,NaN,86681116970,7750023765480440,66 1718522,ANASTASIIA DOROSHINA,ANASTASIIA,DOROSHINA,"SEAPERL BLOCK 8U D39, RAUF ORBAY CADDESI 2/1...",TR,34158,BAKIRKOY,ANDORPSY@GMAIL.COM,5355566836,3315.0,20.14,164.597815,4154.75,NaN,4154.75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Batch-100,2023-02-20,NaN,86681165292,7750023764660478,43819187944,NAGIHAN GUNES,NAGIHAN,GUNES,"E BLOK DAIRE 11, BEYZADEKONAKLARI OZLEM CD, ES...",TR,26240,ESKISEHIR,NAGIHANKANLI007@GMAIL.COM,5415606240,949.0,20.14,47.120159,284.70,90.77,375.47,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Batch-100,2023-02-20,NaN,86681189103,7750023758790495,99519413326,NIMA RAHMANI,NIMA,RAHMANI,"NO23 YAKUPLU BASKENT CADD, NO23 KAT3 DAIRE9, B...",TR,34524,BEYLIKDUUZ,NIMA.RMI70@GMAIL.COM,5344136937,731.0,20.14,36.295929,219.30,90.77,310.07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Batch-100,2023-02-20,NaN,86681189895,7750023760400498,12848391882,BURCU OZKAN,BURCU,OZKAN,"APARTMENT, ATA MAH 1075 SOK 3/12, ANKARA",TR,06460,ANKARA,BRCOZKAN84@GMAIL.COM,5359363071,5525.0,20.14,274.329692,5591.25,NaN,5591.25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Batch-100,2023-02-20,NaN,86680470446,7750023760710078,9002010364088,RUDZANI MUKHELI,RUDZANI,MUKHELI,"UNIT 16 158 FLORA HAASE R, AMOROSA RUIMSIG, GA...",ZA,01724,GAUTENG,MUKHELI@GMAIL.COM,813288275,62.4,20.14,3.098312,18.72,90.77,109.49,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
data.columns

Index(['Batch- ID', 'ExportDate', 'MAWBno', 'Tracking Number',
       'CustomerOrderNo', 'ImporterTAXID', 'ImporterName', 'ImporterFirstName',
       'ImporterLastName', 'ImporterAddress', 'ImporterCountry',
       'ImporterPostcode', 'ImporterCity', 'ImporterEmail', 'ImporterPhone',
       'CustomsValueTRY', 'EURtoTRYRate', 'CustomsValueEUR',
       'CustomsTaxValTRY', 'AdminFeeTRY', 'TotalValueTRY', 'NetReceivedValue',
       'PaymentValControl', 'PaymentReceived', 'ShipmentReady',
       'PaymentMethod', 'PaymentSenderInfo', 'PaymentReceivedDate',
       'PaymentNotes', 'Manifest', 'ManifestDate', 'InvoiceReady',
       'InvoiceDate', 'FullRefund', 'RefundNotes (Iadeler ile Ilgili Notlar)',
       'Notes', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38', 'Unnamed: 39'],
      dtype='object')

In [ ]:
data[['TotalValueTRY', 'NetReceivedValue']]

     TotalValueTRY  NetReceivedValue
0          4154.75               NaN
1           375.47               NaN
2           310.07               NaN
3          5591.25               NaN
4           109.49               NaN
5          4965.30               NaN
6           286.24               NaN
7          5060.20               NaN
8          4431.00               NaN
9          4113.80               NaN
10         4558.40               NaN
11          498.48               NaN
12          398.13               NaN
13          456.03               NaN
14         7777.20               NaN
15          179.86               NaN
16          416.26               NaN
17          358.36               NaN
18          370.66               NaN
19          453.46               NaN
20          808.96               NaN
21          455.86               NaN
22          370.31               NaN
23         4075.45               NaN
24          362.26               NaN
25          334.06               NaN
26         4321.80               NaN
27          374.26               NaN
28          260.86               NaN
29         7116.80               NaN
30          411.46               NaN
31         4730.00               NaN
32          160.06               NaN
33         4010.45               NaN
34          797.97               NaN
35         5511.30               NaN
36          865.17               NaN
37          599.67               NaN
38          927.87               NaN
39          375.23               NaN
40         4785.90               NaN
41          844.75               NaN
42          325.75               NaN
43          447.55               NaN
44          642.25               NaN
45          317.65               NaN
46         6134.00               NaN
47          566.84               NaN
48         4006.55               NaN
49          247.02               NaN
50          566.95               NaN
51          321.39               NaN
52          632.72               NaN
53          206.50               NaN
54          370.67               NaN
55          220.72               NaN
56          604.12               NaN
57          562.72               NaN
58          649.87               NaN
59          236.92               NaN
60          822.97               NaN
61          262.14               NaN
62          854.20               NaN
63          307.01               NaN
64         7633.55               NaN
65          285.52               NaN
66         5307.20               NaN
67          326.32               NaN
68          421.60               NaN
69         5743.88               NaN
70          873.48               NaN
71          950.80               NaN
72          555.47               NaN
73          699.40               NaN
74          702.80               NaN
75          796.68               NaN
76          244.90               NaN
77          926.80               NaN
78          350.50               NaN
79         4510.30               NaN
80          423.70               NaN
81          873.48               NaN
82          351.40               NaN
83          362.37               NaN
84          683.20               NaN
85          853.60               NaN
86          272.03               NaN
87          280.21               NaN
88          395.20               NaN
89          943.90               NaN
90          948.96               NaN
91          276.45               NaN
92          414.28               NaN
93          543.22               NaN
94          931.56               NaN
95          870.02               NaN
96          243.88               NaN
97          292.22               NaN
98          369.52               NaN
99          708.14               NaN
100         304.95               NaN
101         365.68               NaN
102         180.96               NaN
103         146.38               NaN
104         252.28               NaN
105         933.88               NaN
106         566.57               NaN
107         904.88               NaN
108         872.45               NaN
109         336.78               NaN
110         320.41               NaN
111         759.28               NaN
112         861.53               NaN
113         943.38               NaN
114         894.27               NaN
115         836.98               NaN
116         554.14               NaN
117         544.18               NaN
118         836.98               NaN
119         780.28               NaN
120         225.86               NaN
121         599.31               NaN
122         987.28               NaN
123         942.28               NaN
124         246.44               NaN
125         917.38               NaN
126         992.80               NaN
127         763.78               NaN
128         926.68               NaN
129         463.80               NaN
130         925.78               NaN
131         872.45               NaN
132         769.98               NaN
133         373.78               NaN
134         788.08               NaN
135         209.46               NaN
136         414.69               NaN
137        4120.30               NaN
138         901.89               NaN
139         329.49               NaN
140         371.18               NaN
141        4032.55               NaN
142         441.45               NaN
143         940.35               NaN
144         962.55               NaN
145        4199.60               NaN
146         936.45               NaN
147        4009.80               NaN
148         254.85               NaN
149        1001.55               NaN
150         612.15               NaN
151         940.65               NaN
152         571.65               NaN
153        4558.40               NaN
154         401.85               NaN
155         654.45               NaN
156         746.25               NaN
157         866.25               NaN
158         866.25               NaN
159         369.45               NaN
160        4585.70               NaN
161         560.25               NaN
162         271.05               NaN
163        4585.05               NaN
164         181.95               NaN
165         255.45               NaN
166         775.95               NaN
167         866.25               NaN
168         331.65               NaN
169         287.25               NaN
170         717.75               NaN
171         213.62               NaN
172         287.12               NaN
173         668.12               NaN
174         968.42               NaN
175         189.14               NaN
176         351.44               NaN
177         153.49               NaN
178         394.99               NaN
179        4855.45               NaN
180        5422.25               NaN
181         961.92               NaN
182         143.52               NaN
183        7255.90               NaN
184         304.92               NaN
185         866.82               NaN
186         738.42               NaN
187         231.16               NaN
188         454.66               NaN
189         880.96               NaN
190         450.46               NaN
191         572.26               NaN
192         787.36               NaN
193         247.36               NaN
194         280.36               NaN
195         198.76               NaN
196         255.46               NaN
197         271.66               NaN
198        5121.95               NaN
199        5271.45               NaN
200         866.86               NaN
201         450.46               NaN
202         438.46               NaN
203         393.76               NaN
204         561.42               NaN
205         243.72               NaN
206         474.72               NaN
207         867.12               NaN
208         202.92               NaN
209         190.92               NaN
210         271.92               NaN
211         621.12               NaN
212         937.92               NaN
213         730.62               NaN
214        4102.10               NaN
215         970.32               NaN
216         223.32               NaN
217         710.52               NaN
218         239.52               NaN
219         629.22               NaN
220         917.52               NaN
221         991.62               NaN
222         239.52               NaN
223        4646.80               NaN
224         255.72               NaN
225         385.62               NaN
226         698.22               NaN
227         631.22               NaN
228         564.32               NaN
229         459.02               NaN
230        4119.00               NaN
231         227.42               NaN
232         864.92               NaN
233         718.22               NaN
234         191.12               NaN
235         937.82               NaN
236         418.22               NaN
237         544.22               NaN
238         524.72               NaN
239         945.92               NaN
240         683.72               NaN
241         597.32               NaN
242         556.52               NaN
243         830.12               NaN
244         459.02               NaN
245         134.12               NaN
246         491.12               NaN
247         345.32               NaN
248         138.32               NaN
249         580.82               NaN
250         686.42               NaN
251         975.02               NaN
252         630.62               NaN
253         897.02               NaN
254         377.72               NaN
255         938.72               NaN
256         142.22               NaN
257         459.02               NaN
258         337.82               NaN
259         312.19               NaN
260         401.59               NaN
261         888.49               NaN
262         985.99               NaN
263         904.69               NaN
264         872.29               NaN
265         679.09               NaN
266         872.29               NaN
267         872.29               NaN
268         904.69               NaN
269         888.49               NaN
270         904.69               NaN
271         866.89               NaN
272         766.99               NaN
273         492.19               NaN
274        4076.75               NaN
275         921.49               NaN
276         929.59               NaN
277         499.09               NaN
278         734.59               NaN
279         320.59               NaN
280         255.49               NaN
281         568.39               NaN
282         466.69               NaN
283         661.09               NaN
284         666.79               NaN
285        5651.70               NaN
286         446.29               NaN
287         866.89               NaN
288         620.89               NaN
289         433.99               NaN
290        4605.20               NaN
291         150.39               NaN
292         840.39               NaN
293        4016.95               NaN
294         824.49               NaN
295        4832.05               NaN
296         908.43               NaN
297         151.23               NaN
298        4927.60               NaN
299        4093.00               NaN
300         971.13               NaN
301         357.73               NaN
302         745.63               NaN
303         784.63               NaN
304        5152.50               NaN
305         501.13               NaN
306        4800.85               NaN
307        4965.30               NaN
308        4400.45               NaN
309         444.12               NaN
310        5281.20               NaN
311         955.62               NaN
312         509.10               NaN
313         777.00               NaN
314         338.70               NaN
315         980.10               NaN
316         915.60               NaN
317         695.70               NaN
318        1003.80               NaN
319         859.20               NaN
320         383.40               NaN
321         842.70               NaN
322         834.30               NaN
323         939.30               NaN
324         420.90               NaN
325         216.90               NaN
326         923.40               NaN
327         988.50               NaN
328         786.60               NaN
329         599.10               NaN
330         728.40               NaN
331         923.10               NaN
332         553.80               NaN
333         611.40               NaN
334         732.30               NaN
335        4047.50               NaN
336         257.40               NaN
337         306.30               NaN
338         923.10               NaN
339         131.70               NaN
340         419.70               NaN
341         184.50               NaN
342         486.00               NaN
343         984.00               NaN
344         590.40               NaN
345         387.60               NaN
346         245.40               NaN
347         724.20               NaN
348         354.90               NaN
349         648.00               NaN
350        1009.20               NaN
351         828.00               NaN
352         596.10               NaN
353         785.78               NaN
354         746.18               NaN
355         672.39               NaN
356         359.49               NaN
357        9849.40               NaN
358         258.39               NaN
359        5034.20               NaN
360         550.89               NaN
361         172.99               NaN
362         429.79               NaN
363         502.99               NaN
364        9772.05               NaN
365         469.99               NaN
366         970.39               NaN
367         339.19               NaN
368         225.79               NaN
369         931.69               NaN
370         949.09               NaN
371         648.19               NaN
372         501.76               NaN
373         706.66               NaN
374         919.96               NaN
375         858.76               NaN
376         940.36               NaN
377         838.36               NaN
378         388.06               NaN
379         955.96               NaN
380         413.56               NaN
381         355.36               NaN
382         481.96               NaN
383         355.96               NaN
384         567.46               NaN
385         956.26               NaN
386         283.06               NaN
387         291.16               NaN
388         931.96               NaN
389         543.76               NaN
390         355.66               NaN
391         258.16               NaN
392         485.56               NaN
393        4067.65           4067.65
394         801.76               NaN
395         895.06               NaN
396         290.56               NaN
397        4154.75               NaN
398         842.56               NaN
399         867.16               NaN
400         665.86               NaN
401         233.86               NaN
402         339.46               NaN
403         664.06               NaN
404         355.66               NaN
405         294.46               NaN
406         655.96               NaN
407         826.36               NaN
408         355.66               NaN
409         877.66               NaN
410         657.76               NaN
411         307.06               NaN
412         274.66               NaN
413         258.16               NaN
414         462.16               NaN
415        6633.20               NaN
416        1005.16               NaN
417         657.76               NaN
418         876.46               NaN
419         983.26               NaN
420         542.26               NaN
421         728.86               NaN
422         388.06               NaN
423         339.46               NaN
424         578.26               NaN
425         705.41               NaN
426         526.91               NaN
427         892.01               NaN
428         342.11               NaN
429         997.61               NaN
430         479.51               NaN
431         843.41               NaN
432         421.61               NaN
433         242.81               NaN
434         324.71               NaN
435         259.01               NaN
436         210.41               NaN
437         661.01               NaN
438         681.41               NaN
439         900.41               NaN
440        1024.91               NaN
441         275.21               NaN
442         721.61               NaN
443         462.11               NaN
444         455.21               NaN
445        1016.81               NaN
446         157.61               NaN
447         624.41               NaN
448         811.31               NaN
449        1015.01               NaN
450         364.91               NaN
451         786.71               NaN
452         332.21               NaN
453         924.41               NaN
454         985.61               NaN
455         555.41               NaN
456         632.81               NaN
457         405.11               NaN
458         568.01               NaN
459         997.91               NaN
460         997.61               NaN
461         957.71               NaN
462         429.41               NaN
463         947.21               NaN
464         307.91               NaN
465         794.99               NaN
466        4542.80               NaN
467         560.39               NaN
468         957.29               NaN
469        4964.00               NaN
470         998.99               NaN
471         356.69               NaN
472         927.29               NaN
473        1005.89               NaN
474         884.39               NaN
475         962.99               NaN
476         543.29               NaN
477         665.99               NaN
478         234.89               NaN
479         412.79               NaN
480         930.59               NaN
481        4119.65               NaN
482         778.79               NaN
483         234.89               NaN
484         949.49               NaN
485         673.19               NaN
486         510.89               NaN
487         437.99               NaN
488         949.49               NaN
489         251.09               NaN
490         699.29               NaN
491         933.29               NaN
492         892.49               NaN
493         569.09               NaN
494         829.49               NaN
495         259.19               NaN
496         266.73               NaN
497         659.73               NaN
498         430.23               NaN
499         804.03               NaN
500         666.33               NaN
501         738.33               NaN
502         845.13               NaN
503         820.23               NaN
504         550.83               NaN
505         737.43               NaN
506         616.53               NaN
507        4225.60               NaN
508        4902.25               NaN
509         498.33          50356.00
510         234.33          23679.00
511        4093.00               NaN
512        4216.50               NaN
513        4189.85               NaN
514         762.03               NaN
515         266.73               NaN
516         932.38               NaN
517         347.08          35072.00
518         843.28               NaN
519         636.58               NaN
520         348.28               NaN
521         453.88               NaN
522         636.58               NaN
523         835.18               NaN
524         315.88               NaN
525         177.88               NaN
526         266.98               NaN
527         779.38               NaN
528         242.68               NaN
529         316.18               NaN
530         762.58               NaN
531         870.28          87942.00
532         437.38               NaN
533        1040.98               NaN
534         299.68               NaN
535         291.28               NaN
536         437.68               NaN
537         486.28               NaN
538         956.98               NaN

In [ ]:
data['NetReceivedValue']= data['NetReceivedValue'].fillna("0")

In [ ]:
a =data['TotalValueTRY'].to_list()
b = data['NetReceivedValue'].to_list()
result = []

In [ ]:
for y,x in zip(a,b):
    try:
        if x >= y:
          result.append(True)
        else:
          result.append(False)
    except:
          result.append("Bos")

In [ ]:
data["kiyas"]= result

In [ ]:
data["kiyas"].value_counts()

Bos      635
True     154
False      1
Name: kiyas, dtype: int64

In [ ]:
data["PaymentValControl"].value_counts(dropna=False)

True    550
NaN     240
Name: PaymentValControl, dtype: int64

In [ ]:
data[['kiyas','PaymentValControl']]

     kiyas PaymentValControl
0      Bos               NaN
1      Bos               NaN
2      Bos               NaN
3      Bos               NaN
4      Bos               NaN
5      Bos               NaN
6      Bos               NaN
7      Bos               NaN
8      Bos               NaN
9      Bos               NaN
10     Bos               NaN
11     Bos               NaN
12     Bos               NaN
13     Bos               NaN
14     Bos               NaN
15     Bos               NaN
16     Bos               NaN
17     Bos               NaN
18     Bos               NaN
19     Bos               NaN
20     Bos               NaN
21     Bos               NaN
22     Bos              True
23     Bos               NaN
24     Bos               NaN
25     Bos               NaN
26     Bos               NaN
27     Bos               NaN
28     Bos               NaN
29     Bos               NaN
30     Bos               NaN
31     Bos               NaN
32     Bos              True
33     Bos               NaN
34     Bos               NaN
35     Bos               NaN
36     Bos               NaN
37     Bos               NaN
38     Bos               NaN
39     Bos               NaN
40     Bos               NaN
41     Bos              True
42     Bos              True
43     Bos               NaN
44     Bos              True
45     Bos              True
46     Bos               NaN
47     Bos              True
48     Bos               NaN
49     Bos              True
50     Bos               NaN
51     Bos              True
52     Bos              True
53     Bos              True
54     Bos              True
55     Bos               NaN
56     Bos              True
57     Bos               NaN
58     Bos              True
59     Bos              True
60     Bos              True
61     Bos              True
62     Bos              True
63     Bos              True
64     Bos               NaN
65     Bos               NaN
66     Bos               NaN
67     Bos              True
68     Bos              True
69     Bos              True
70     Bos              True
71     Bos              True
72     Bos              True
73     Bos              True
74     Bos              True
75     Bos              True
76     Bos              True
77     Bos              True
78     Bos              True
79     Bos               NaN
80     Bos              True
81     Bos              True
82     Bos              True
83     Bos              True
84     Bos              True
85     Bos              True
86     Bos              True
87     Bos              True
88     Bos               NaN
89     Bos               NaN
90     Bos              True
91     Bos              True
92     Bos              True
93     Bos              True
94     Bos              True
95     Bos              True
96     Bos              True
97     Bos              True
98     Bos              True
99     Bos              True
100    Bos              True
101    Bos              True
102    Bos              True
103    Bos              True
104    Bos              True
105    Bos              True
106    Bos              True
107    Bos              True
108    Bos              True
109    Bos              True
110    Bos              True
111    Bos              True
112    Bos              True
113    Bos              True
114    Bos              True
115    Bos              True
116    Bos              True
117    Bos              True
118    Bos              True
119    Bos              True
120    Bos              True
121    Bos              True
122    Bos              True
123    Bos              True
124    Bos              True
125    Bos              True
126    Bos              True
127    Bos              True
128    Bos              True
129    Bos              True
130    Bos              True
131    Bos              True
132    Bos              True
133    Bos               NaN
134    Bos              True
135    Bos              True
136    Bos               NaN
137    Bos               NaN
138    Bos               NaN
139    Bos               NaN
140    Bos               NaN
141    Bos               NaN
142    Bos              True
143    Bos               NaN
144    Bos               NaN
145    Bos               NaN
146    Bos               NaN
147    Bos               NaN
148    Bos               NaN
149    Bos               NaN
150    Bos              True
151    Bos               NaN
152    Bos               NaN
153    Bos               NaN
154    Bos               NaN
155    Bos               NaN
156    Bos              True
157    Bos               NaN
158    Bos               NaN
159    Bos               NaN
160    Bos               NaN
161    Bos               NaN
162    Bos               NaN
163    Bos               NaN
164    Bos               NaN
165    Bos              True
166    Bos               NaN
167    Bos               NaN
168    Bos               NaN
169    Bos               NaN
170    Bos              True
171    Bos               NaN
172    Bos               NaN
173    Bos              True
174    Bos               NaN
175    Bos               NaN
176    Bos               NaN
177    Bos              True
178    Bos              True
179    Bos               NaN
180    Bos               NaN
181    Bos               NaN
182    Bos               NaN
183    Bos               NaN
184    Bos               NaN
185    Bos              True
186    Bos               NaN
187    Bos              True
188    Bos               NaN
189    Bos              True
190    Bos               NaN
191    Bos              True
192    Bos              True
193    Bos              True
194    Bos              True
195    Bos               NaN
196    Bos              True
197    Bos              True
198    Bos               NaN
199    Bos               NaN
200    Bos               NaN
201    Bos              True
202    Bos              True
203    Bos              True
204    Bos               NaN
205    Bos               NaN
206    Bos               NaN
207    Bos              True
208    Bos              True
209    Bos              True
210    Bos              True
211    Bos              True
212    Bos              True
213    Bos              True
214    Bos               NaN
215    Bos              True
216    Bos              True
217    Bos              True
218    Bos              True
219    Bos              True
220    Bos              True
221    Bos              True
222    Bos              True
223    Bos               NaN
224    Bos              True
225    Bos              True
226    Bos              True
227    Bos              True
228    Bos              True
229    Bos              True
230    Bos              True
231    Bos               NaN
232    Bos              True
233    Bos              True
234    Bos              True
235    Bos              True
236    Bos              True
237    Bos              True
238    Bos              True
239    Bos              True
240    Bos              True
241    Bos              True
242    Bos              True
243    Bos              True
244    Bos              True
245    Bos              True
246    Bos              True
247    Bos              True
248    Bos              True
249    Bos              True
250    Bos              True
251    Bos              True
252    Bos              True
253    Bos              True
254    Bos              True
255    Bos              True
256    Bos              True
257    Bos              True
258    Bos              True
259    Bos              True
260    Bos              True
261    Bos              True
262    Bos              True
263    Bos              True
264    Bos              True
265    Bos               NaN
266    Bos              True
267    Bos              True
268    Bos              True
269    Bos              True
270    Bos              True
271    Bos              True
272    Bos              True
273    Bos              True
274    Bos               NaN
275    Bos              True
276    Bos              True
277    Bos              True
278    Bos              True
279    Bos              True
280    Bos              True
281    Bos              True
282    Bos              True
283    Bos              True
284    Bos              True
285    Bos               NaN
286    Bos              True
287    Bos              True
288    Bos              True
289    Bos              True
290    Bos               NaN
291    Bos               NaN
292    Bos               NaN
293    Bos               NaN
294    Bos              True
295    Bos               NaN
296    Bos               NaN
297    Bos               NaN
298    Bos               NaN
299    Bos               NaN
300    Bos               NaN
301    Bos               NaN
302    Bos               NaN
303    Bos               NaN
304    Bos               NaN
305    Bos              True
306    Bos               NaN
307    Bos               NaN
308    Bos               NaN
309    Bos               NaN
310    Bos               NaN
311    Bos              True
312    Bos              True
313    Bos              True
314    Bos              True
315    Bos              True
316    Bos              True
317    Bos              True
318    Bos              True
319    Bos              True
320    Bos              True
321    Bos              True
322    Bos              True
323    Bos              True
324    Bos              True
325    Bos              True
326    Bos              True
327    Bos              True
328    Bos              True
329    Bos              True
330    Bos              True
331    Bos              True
332    Bos              True
333    Bos              True
334    Bos              True
335    Bos               NaN
336    Bos              True
337    Bos              True
338    Bos              True
339    Bos              True
340    Bos              True
341    Bos              True
342    Bos              True
343    Bos              True
344    Bos              True
345    Bos              True
346    Bos              True
347    Bos              True
348    Bos              True
349    Bos              True
350    Bos              True
351    Bos              True
352    Bos              True
353    Bos              True
354    Bos              True
355    Bos              True
356    Bos               NaN
357    Bos               NaN
358    Bos               NaN
359    Bos               NaN
360    Bos              True
361    Bos              True
362    Bos               NaN
363    Bos               NaN
364    Bos               NaN
365    Bos              True
366    Bos              True
367    Bos              True
368    Bos               NaN
369    Bos              True
370    Bos              True
371    Bos               NaN
372    Bos               NaN
373    Bos              True
374    Bos              True
375    Bos              True
376    Bos              True
377    Bos              True
378    Bos              True
379    Bos              True
380    Bos              True
381    Bos              True
382    Bos              True
383    Bos              True
384    Bos               NaN
385    Bos               NaN
386    Bos              True
387    Bos              True
388    Bos              True
389    Bos              True
390    Bos              True
391    Bos              True
392    Bos              True
393   True              True
394    Bos              True
395    Bos              True
396    Bos               NaN
397    Bos               NaN
398    Bos              True
399    Bos              True
400    Bos              True
401    Bos               NaN
402    Bos              True
403    Bos              True
404    Bos               NaN
405    Bos              True
406    Bos              True
407    Bos              True
408    Bos              True
409    Bos              True
410    Bos              True
411    Bos              True
412    Bos              True
413    Bos              True
414    Bos              True
415    Bos               NaN
416    Bos               NaN
417    Bos              True
418    Bos              True
419    Bos              True
420    Bos              True
421    Bos              True
422    Bos              True
423    Bos              True
424    Bos              True
425    Bos              True
426    Bos              True
427    Bos              True
428    Bos              True
429    Bos              True
430    Bos              True
431    Bos              True
432    Bos              True
433    Bos              True
434    Bos              True
435    Bos              True
436    Bos              True
437    Bos              True
438    Bos              True
439    Bos              True
440    Bos              True
441    Bos              True
442    Bos              True
443    Bos              True
444    Bos              True
445    Bos              True
446    Bos              True
447    Bos              True
448    Bos              True
449    Bos              True
450    Bos              True
451    Bos              True
452    Bos              True
453    Bos              True
454    Bos              True
455    Bos              True
456    Bos              True
457    Bos              True
458    Bos              True
459    Bos              True
460    Bos              True
461    Bos              True
462    Bos              True
463    Bos              True
464    Bos              True
465    Bos               NaN
466    Bos              True
467    Bos              True
468    Bos              True
469    Bos               NaN
470    Bos              True
471    Bos               NaN
472    Bos              True
473    Bos              True
474    Bos              True
475    Bos              True
476    Bos              True
477    Bos              True
478    Bos              True
479    Bos              True
480    Bos              True
481    Bos               NaN
482    Bos              True
483    Bos              True
484    Bos              True
485    Bos              True
486    Bos              True
487    Bos              True
488    Bos              True
489    Bos              True
490    Bos              True
491    Bos              True
492    Bos              True
493    Bos              True
494    Bos              True
495    Bos              True
496    Bos               NaN
497    Bos              True
498    Bos              True
499    Bos              True
500    Bos              True
501    Bos              True
502    Bos              True
503    Bos              True
504    Bos              True
505    Bos              True
506    Bos              True
507    Bos               NaN
508    Bos               NaN
509   True              True
510   True              True
511    Bos               NaN
512    Bos               NaN
513    Bos               NaN
514    Bos              True
515    Bos               NaN
516    Bos              True
517   True              True
518    Bos              True
519    Bos              True
520    Bos              True
521    Bos              True
522    Bos               NaN
523    Bos              True
524    Bos              True
525    Bos              True
526    Bos              True
527    Bos              True
528    Bos              True
529    Bos              True
530    Bos              True
531   True              True
532    Bos              True
533    Bos              True
534    Bos              True
535    Bos              True
536    Bos              True
537    Bos              True
538    Bos              True
539    Bos              True
540    Bos              True
541    Bos               NaN
542    Bos               NaN
543   True              True
544    Bos              True
545    Bos              True
546    Bos              True
547   True              True
548    Bos               NaN
549   True              True
550   True              True
551   True              True
552    Bos              True
553    Bos              True
554    Bos              True
555    Bos              True
556    Bos              True
557   True              True
558   True              True
559    Bos               NaN
560    Bos              True
561   True              True
562    Bos              True
563    Bos               NaN
564    Bos              True
565   True              True
566    Bos              True
567    Bos              True
568    Bos              True
569    Bos              True
570    Bos              True
571    Bos              True
572   True              True
573    Bos              True
574   True              True
575   True              True
576    Bos               NaN
577   True              True
578   True              True
579    Bos               NaN
580   True              True
581   True              True
582   True              True
583   True              True
584   True              True
585    Bos               NaN
586    Bos               NaN
587   True              True
588   True              True
589   True              True
590   True              True
591   True              True
592   True              True
593   True              True
594   True              True
595   True              True
596   True              True
597   True              True
598   True              True
599   True              True
600   True              True
601    Bos               NaN
602   True              True
603    Bos               NaN
604    Bos               NaN
605    Bos               NaN
606    Bos               NaN
607    Bos               NaN
608    Bos               NaN
609    Bos               NaN
610   True              True
611   True              True
612    Bos               NaN
613    Bos               NaN
614    Bos               NaN
615    Bos               NaN
616    Bos               NaN
617    Bos               NaN
618   True              True
619   True              True
620   True              True
621   True              True
622   True              True
623   True              True
624   True              True
625   True              True
626   True              True
627   True              True
628   True              True
629   True              True
630   True              True
631   True              True
632    Bos               NaN
633   True              True
634   True              True
635   True              True
636   True              True
637    Bos               NaN
638   True              True
639   True              True
640   True              True
641   True              True
642   True              True
643   True              True
644   True              True
645   True              True
646   True              True
647   True              True
648    Bos               NaN
649   True              True
650   True              True
651   True              True
652   True              True
653   True              True
654   True              True
655   True              True
656   True              True
657   True              True
658   True              True
659   True              True
660   True              True
661   True              True
662   True              True
663   True              True
664   True              True
665   True              True
666   True              True
667   True              True
668   True              True
669   True              True
670   True              True
671    Bos               NaN
672   True              True
673   True              True
674   True              True
675    Bos               NaN
676   True              True
677   True              True
678   True              True
679   True              True
680   True              True
681   True              True
682   True              True
683    Bos               NaN
684    Bos               NaN
685   True              True
686   True              True
687    Bos               NaN

In [ ]:
df = data[["TotalValueTRY","NetReceivedValue","PaymentValControl","kiyas"]]

In [ ]:
df[df["kiyas"]==True]

     TotalValueTRY NetReceivedValue PaymentValControl kiyas
393        4067.65          4067.65              True  True
509         498.33          50356.0              True  True
510         234.33          23679.0              True  True
517         347.08          35072.0              True  True
531         870.28          87942.0              True  True
543         315.58          31889.0              True  True
547         867.28          87639.0              True  True
549         892.18          90155.0              True  True
550         519.28          52473.0              True  True
551         623.98          63053.0              True  True
557         599.68          59968.0              True  True
558         266.68          26948.0              True  True
561         969.28          97946.0              True  True
565         421.18           4256.0              True  True
572         469.48          47441.0              True  True
574         696.79          70411.0              True  True
575         991.99         100241.0              True  True
577         864.79          87387.0              True  True
578         310.99          31426.0              True  True
580         701.59          70159.0              True  True
581         961.69          97179.0              True  True
582         242.29          24229.0              True  True
583         640.39          64039.0              True  True
584         591.49          59149.0              True  True
587         566.89          57284.0              True  True
588        1037.59         103759.0              True  True
589         867.49          86749.0              True  True
590         869.89          86989.0              True  True
591         496.99          49699.0              True  True
592         899.59          90904.0              True  True
593         964.69          97482.0              True  True
594        1013.59         101359.0              True  True
595         847.69          85659.0              True  True
596         664.39          67137.0              True  True
597         713.29          72078.0              True  True
598         404.59          40459.0              True  True
599         469.69          47462.0              True  True
600         436.99          44158.0              True  True
602         916.74          91674.0              True  True
610         258.90           2589.0              True  True
611        1031.70         104253.0              True  True
618         701.65          70902.0              True  True
619        4407.60         445388.0              True  True
620         340.15          34015.0              True  True
621         758.35          75835.0              True  True
622         819.00           8276.0              True  True
623         446.24          45093.0              True  True
624         373.04           3733.0              True  True
625         620.54          62706.0              True  True
626         689.84          69708.0              True  True
627         553.04          55885.0              True  True
628         640.94          64767.0              True  True
629        1041.74         104174.0              True  True
630         235.04          23751.0              True  True
631         600.44          60044.0              True  True
633         406.04           4103.0              True  True
634         779.84          77984.0              True  True
635         937.64          93764.0              True  True
636         707.84          71527.0              True  True
638         421.64          42607.0              True  True
639         243.14          24314.0              True  True
640         333.14          33314.0              True  True
641         941.54          95143.0              True  True
642         259.34          25934.0              True  True
643        1033.64         104449.0              True  True
644         681.74           6889.0              True  True
645         405.44           4097.0              True  True
646         506.84          51216.0              True  True
647         901.04          90104.0              True  True
649         519.14          52459.0              True  True
650         308.24          31148.0              True  True
651         811.64          82016.0              True  True
652         904.34          91384.0              True  True
653         450.14          45014.0              True  True
654        1010.54          1010.54              True  True
655         275.54          28381.0              True  True
656         579.74          58583.0              True  True
657         714.14          72164.0              True  True
658         389.84          39393.0              True  True
659         918.14          92778.0              True  True
660         259.34          26206.0              True  True
661         811.64          81164.0              True  True
662         649.34          65616.0              True  True
663         622.94          62948.0              True  True
664         616.64          62311.0              True  True
665         892.34          90171.0              True  True
666         381.14          38514.0              True  True
667         754.64          76256.0              True  True
668         811.34          81986.0              True  True
669         949.34          94934.0              True  True
670         754.64          76256.0              True  True
672         689.99          69723.0              True  True
673         194.69          19673.0              True  True
674         570.29          57628.0              True  True
676         341.06          35129.0              True  True
677         667.46          67447.0              True  True
678         982.46            983.0              True  True
679         689.96           6972.0              True  True
680         738.56          73856.0              True  True
681         503.36            504.0              True  True
682         267.86          27067.0              True  True
685         803.66           8121.0              True  True
686         649.46          64946.0              True  True
688         426.26          43074.0              True  True
690         259.76          25976.0              True  True
691         586.16          59231.0              True  True
692         941.66          95155.0              True  True
693         218.96          22126.0              True  True
694         463.76          46863.0              True  True
695         625.16          63172.0              True  True
696         982.46          98246.0              True  True
697         694.16          70145.0              True  True
698         872.01          87201.0              True  True
699         488.01          48801.0              True  True
700         741.51           7493.0              True  True
701         276.81            280.0              True  True
703         268.71          27153.0              True  True
704         609.81          60981.0              True  True
705         585.51          59166.0              True  True
706         869.31          87844.0              True  True
707         885.81          88581.0              True  True
709         881.31          89056.0              True  True
710         205.71          20571.0              True  True
711         908.61          90861.0              True  True
712         358.11          36187.0              True  True
713         286.11          28611.0              True  True
714         709.11          70911.0              True  True
715         406.71          40671.0              True  True
716         187.71          18968.0              True  True
717         463.71          46858.0              True  True
718         805.41          82957.0              True  True
719         350.01          35001.0              True  True
720         902.13           9116.0              True  True
721         362.73          73308.0              True  True
723         271.23          27123.0              True  True
724        4628.60          93544.0              True  True
725         147.33          29776.0              True  True
726         635.43           6421.0              True  True
729         342.33          34233.0              True  True
732         594.03          60027.0              True  True
733         480.33          48033.0              True  True
735         781.23          78123.0              True  True
737         593.43          59966.0              True  True
738         525.63           1052.0              True  True
739         660.63          66757.0              True  True
740         543.33          54903.0              True  True
741         700.53          70789.0              True  True
742         326.73          66032.0              True  True
743         595.23          60148.0              True  True
744         943.23          95313.0              True  True
747        1008.03         101861.0              True  True
748         790.83          79913.0              True  True
749         845.73          85461.0              True  True
750         642.63         129876.0              True  True

In [ ]:
df[df["kiyas"]==False]
# burda yazdigim kod calisirken girilen verilerde hata oldugu gorulmektedir.
#

     TotalValueTRY NetReceivedValue PaymentValControl  kiyas
745        1023.93              0.0              True  False

In [ ]:
df[df["kiyas"]== "Bos"]

     TotalValueTRY NetReceivedValue PaymentValControl kiyas
0          4154.75                0               NaN   Bos
1           375.47                0               NaN   Bos
2           310.07                0               NaN   Bos
3          5591.25                0               NaN   Bos
4           109.49                0               NaN   Bos
5          4965.30                0               NaN   Bos
6           286.24                0               NaN   Bos
7          5060.20                0               NaN   Bos
8          4431.00                0               NaN   Bos
9          4113.80                0               NaN   Bos
10         4558.40                0               NaN   Bos
11          498.48                0               NaN   Bos
12          398.13                0               NaN   Bos
13          456.03                0               NaN   Bos
14         7777.20                0               NaN   Bos
15          179.86                0               NaN   Bos
16          416.26                0               NaN   Bos
17          358.36                0               NaN   Bos
18          370.66                0               NaN   Bos
19          453.46                0               NaN   Bos
20          808.96                0               NaN   Bos
21          455.86                0               NaN   Bos
22          370.31                0              True   Bos
23         4075.45                0               NaN   Bos
24          362.26                0               NaN   Bos
25          334.06                0               NaN   Bos
26         4321.80                0               NaN   Bos
27          374.26                0               NaN   Bos
28          260.86                0               NaN   Bos
29         7116.80                0               NaN   Bos
30          411.46                0               NaN   Bos
31         4730.00                0               NaN   Bos
32          160.06                0              True   Bos
33         4010.45                0               NaN   Bos
34          797.97                0               NaN   Bos
35         5511.30                0               NaN   Bos
36          865.17                0               NaN   Bos
37          599.67                0               NaN   Bos
38          927.87                0               NaN   Bos
39          375.23                0               NaN   Bos
40         4785.90                0               NaN   Bos
41          844.75                0              True   Bos
42          325.75                0              True   Bos
43          447.55                0               NaN   Bos
44          642.25                0              True   Bos
45          317.65                0              True   Bos
46         6134.00                0               NaN   Bos
47          566.84                0              True   Bos
48         4006.55                0               NaN   Bos
49          247.02                0              True   Bos
50          566.95                0               NaN   Bos
51          321.39                0              True   Bos
52          632.72                0              True   Bos
53          206.50                0              True   Bos
54          370.67                0              True   Bos
55          220.72                0               NaN   Bos
56          604.12                0              True   Bos
57          562.72                0               NaN   Bos
58          649.87                0              True   Bos
59          236.92                0              True   Bos
60          822.97                0              True   Bos
61          262.14                0              True   Bos
62          854.20                0              True   Bos
63          307.01                0              True   Bos
64         7633.55                0               NaN   Bos
65          285.52                0               NaN   Bos
66         5307.20                0               NaN   Bos
67          326.32                0              True   Bos
68          421.60                0              True   Bos
69         5743.88                0              True   Bos
70          873.48                0              True   Bos
71          950.80                0              True   Bos
72          555.47                0              True   Bos
73          699.40                0              True   Bos
74          702.80                0              True   Bos
75          796.68                0              True   Bos
76          244.90                0              True   Bos
77          926.80                0              True   Bos
78          350.50                0              True   Bos
79         4510.30                0               NaN   Bos
80          423.70                0              True   Bos
81          873.48                0              True   Bos
82          351.40                0              True   Bos
83          362.37                0              True   Bos
84          683.20                0              True   Bos
85          853.60                0              True   Bos
86          272.03                0              True   Bos
87          280.21                0              True   Bos
88          395.20                0               NaN   Bos
89          943.90                0               NaN   Bos
90          948.96                0              True   Bos
91          276.45                0              True   Bos
92          414.28                0              True   Bos
93          543.22                0              True   Bos
94          931.56                0              True   Bos
95          870.02                0              True   Bos
96          243.88                0              True   Bos
97          292.22                0              True   Bos
98          369.52                0              True   Bos
99          708.14                0              True   Bos
100         304.95                0              True   Bos
101         365.68                0              True   Bos
102         180.96                0              True   Bos
103         146.38                0              True   Bos
104         252.28                0              True   Bos
105         933.88                0              True   Bos
106         566.57                0              True   Bos
107         904.88                0              True   Bos
108         872.45                0              True   Bos
109         336.78                0              True   Bos
110         320.41                0              True   Bos
111         759.28                0              True   Bos
112         861.53                0              True   Bos
113         943.38                0              True   Bos
114         894.27                0              True   Bos
115         836.98                0              True   Bos
116         554.14                0              True   Bos
117         544.18                0              True   Bos
118         836.98                0              True   Bos
119         780.28                0              True   Bos
120         225.86                0              True   Bos
121         599.31                0              True   Bos
122         987.28                0              True   Bos
123         942.28                0              True   Bos
124         246.44                0              True   Bos
125         917.38                0              True   Bos
126         992.80                0              True   Bos
127         763.78                0              True   Bos
128         926.68                0              True   Bos
129         463.80                0              True   Bos
130         925.78                0              True   Bos
131         872.45                0              True   Bos
132         769.98                0              True   Bos
133         373.78                0               NaN   Bos
134         788.08                0              True   Bos
135         209.46                0              True   Bos
136         414.69                0               NaN   Bos
137        4120.30                0               NaN   Bos
138         901.89                0               NaN   Bos
139         329.49                0               NaN   Bos
140         371.18                0               NaN   Bos
141        4032.55                0               NaN   Bos
142         441.45                0              True   Bos
143         940.35                0               NaN   Bos
144         962.55                0               NaN   Bos
145        4199.60                0               NaN   Bos
146         936.45                0               NaN   Bos
147        4009.80                0               NaN   Bos
148         254.85                0               NaN   Bos
149        1001.55                0               NaN   Bos
150         612.15                0              True   Bos
151         940.65                0               NaN   Bos
152         571.65                0               NaN   Bos
153        4558.40                0               NaN   Bos
154         401.85                0               NaN   Bos
155         654.45                0               NaN   Bos
156         746.25                0              True   Bos
157         866.25                0               NaN   Bos
158         866.25                0               NaN   Bos
159         369.45                0               NaN   Bos
160        4585.70                0               NaN   Bos
161         560.25                0               NaN   Bos
162         271.05                0               NaN   Bos
163        4585.05                0               NaN   Bos
164         181.95                0               NaN   Bos
165         255.45                0              True   Bos
166         775.95                0               NaN   Bos
167         866.25                0               NaN   Bos
168         331.65                0               NaN   Bos
169         287.25                0               NaN   Bos
170         717.75                0              True   Bos
171         213.62                0               NaN   Bos
172         287.12                0               NaN   Bos
173         668.12                0              True   Bos
174         968.42                0               NaN   Bos
175         189.14                0               NaN   Bos
176         351.44                0               NaN   Bos
177         153.49                0              True   Bos
178         394.99                0              True   Bos
179        4855.45                0               NaN   Bos
180        5422.25                0               NaN   Bos
181         961.92                0               NaN   Bos
182         143.52                0               NaN   Bos
183        7255.90                0               NaN   Bos
184         304.92                0               NaN   Bos
185         866.82                0              True   Bos
186         738.42                0               NaN   Bos
187         231.16                0              True   Bos
188         454.66                0               NaN   Bos
189         880.96                0              True   Bos
190         450.46                0               NaN   Bos
191         572.26                0              True   Bos
192         787.36                0              True   Bos
193         247.36                0              True   Bos
194         280.36                0              True   Bos
195         198.76                0               NaN   Bos
196         255.46                0              True   Bos
197         271.66                0              True   Bos
198        5121.95                0               NaN   Bos
199        5271.45                0               NaN   Bos
200         866.86                0               NaN   Bos
201         450.46                0              True   Bos
202         438.46                0              True   Bos
203         393.76                0              True   Bos
204         561.42                0               NaN   Bos
205         243.72                0               NaN   Bos
206         474.72                0               NaN   Bos
207         867.12                0              True   Bos
208         202.92                0              True   Bos
209         190.92                0              True   Bos
210         271.92                0              True   Bos
211         621.12                0              True   Bos
212         937.92                0              True   Bos
213         730.62                0              True   Bos
214        4102.10                0               NaN   Bos
215         970.32                0              True   Bos
216         223.32                0              True   Bos
217         710.52                0              True   Bos
218         239.52                0              True   Bos
219         629.22                0              True   Bos
220         917.52                0              True   Bos
221         991.62                0              True   Bos
222         239.52                0              True   Bos
223        4646.80                0               NaN   Bos
224         255.72                0              True   Bos
225         385.62                0              True   Bos
226         698.22                0              True   Bos
227         631.22                0              True   Bos
228         564.32                0              True   Bos
229         459.02                0              True   Bos
230        4119.00                0              True   Bos
231         227.42                0               NaN   Bos
232         864.92                0              True   Bos
233         718.22                0              True   Bos
234         191.12                0              True   Bos
235         937.82                0              True   Bos
236         418.22                0              True   Bos
237         544.22                0              True   Bos
238         524.72                0              True   Bos
239         945.92                0              True   Bos
240         683.72                0              True   Bos
241         597.32                0              True   Bos
242         556.52                0              True   Bos
243         830.12                0              True   Bos
244         459.02                0              True   Bos
245         134.12                0              True   Bos
246         491.12                0              True   Bos
247         345.32                0              True   Bos
248         138.32                0              True   Bos
249         580.82                0              True   Bos
250         686.42                0              True   Bos
251         975.02                0              True   Bos
252         630.62                0              True   Bos
253         897.02                0              True   Bos
254         377.72                0              True   Bos
255         938.72                0              True   Bos
256         142.22                0              True   Bos
257         459.02                0              True   Bos
258         337.82                0              True   Bos
259         312.19                0              True   Bos
260         401.59                0              True   Bos
261         888.49                0              True   Bos
262         985.99                0              True   Bos
263         904.69                0              True   Bos
264         872.29                0              True   Bos
265         679.09                0               NaN   Bos
266         872.29                0              True   Bos
267         872.29                0              True   Bos
268         904.69                0              True   Bos
269         888.49                0              True   Bos
270         904.69                0              True   Bos
271         866.89                0              True   Bos
272         766.99                0              True   Bos
273         492.19                0              True   Bos
274        4076.75                0               NaN   Bos
275         921.49                0              True   Bos
276         929.59                0              True   Bos
277         499.09                0              True   Bos
278         734.59                0              True   Bos
279         320.59                0              True   Bos
280         255.49                0              True   Bos
281         568.39                0              True   Bos
282         466.69                0              True   Bos
283         661.09                0              True   Bos
284         666.79                0              True   Bos
285        5651.70                0               NaN   Bos
286         446.29                0              True   Bos
287         866.89                0              True   Bos
288         620.89                0              True   Bos
289         433.99                0              True   Bos
290        4605.20                0               NaN   Bos
291         150.39                0               NaN   Bos
292         840.39                0               NaN   Bos
293        4016.95                0               NaN   Bos
294         824.49                0              True   Bos
295        4832.05                0               NaN   Bos
296         908.43                0               NaN   Bos
297         151.23                0               NaN   Bos
298        4927.60                0               NaN   Bos
299        4093.00                0               NaN   Bos
300         971.13                0               NaN   Bos
301         357.73                0               NaN   Bos
302         745.63                0               NaN   Bos
303         784.63                0               NaN   Bos
304        5152.50                0               NaN   Bos
305         501.13                0              True   Bos
306        4800.85                0               NaN   Bos
307        4965.30                0               NaN   Bos
308        4400.45                0               NaN   Bos
309         444.12                0               NaN   Bos
310        5281.20                0               NaN   Bos
311         955.62                0              True   Bos
312         509.10                0              True   Bos
313         777.00                0              True   Bos
314         338.70                0              True   Bos
315         980.10                0              True   Bos
316         915.60                0              True   Bos
317         695.70                0              True   Bos
318        1003.80                0              True   Bos
319         859.20                0              True   Bos
320         383.40                0              True   Bos
321         842.70                0              True   Bos
322         834.30                0              True   Bos
323         939.30                0              True   Bos
324         420.90                0              True   Bos
325         216.90                0              True   Bos
326         923.40                0              True   Bos
327         988.50                0              True   Bos
328         786.60                0              True   Bos
329         599.10                0              True   Bos
330         728.40                0              True   Bos
331         923.10                0              True   Bos

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 790 entries, 0 to 789
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   TotalValueTRY      790 non-null    float64
 1   NetReceivedValue   790 non-null    object
 2   PaymentValControl  550 non-null    object
 3   kiyas              790 non-null    object
dtypes: float64(1), object(3)
memory usage: 24.8+ KB